parameters:
  unityProject: true

jobs:
- job: Job
  displayName: CD
  pool:
    vmImage: windows-latest
  steps:
  - template: ../steps/cd.yml
    parameters:
      unityProject: ${{ parameters.unityProject }}
